name: graphes
on: [push]
jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Installation de graphviz
run: sudo apt update && sudo apt install -y graphviz

- name: Check out repository code
uses: actions/checkout@v3

- name: Lancement graphviz
run: ./run1.sh g1

- name: Upload SVG files
     uses: actions/upload-artifact@v4
     with:
       name: graphes-svg
       path: '*.svg'
