name: graphes
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Installation de Graphviz
        run: sudo apt update && sudo apt install -y graphviz

      - name: Lancement Graphviz
        run: ./run1.sh g1

      - name: Upload SVG files
        uses: actions/upload-artifact@v4
        with:
          name: graphes-svg
          path: 'g1.svg'

